sipeed/NanoKVM

web/src/i18n/languages.ts, web/src/i18n/locales/ko.ts
=> Translation

web/src/i18n/languages.ts, web/src/i18n/locales/it.ts
This commit adds the support to Italian language, for Italian users.
=> Add support for Italian language

web/src/i18n/languages.ts, web/src/i18n/locales/es.ts
Added Spanish translation.
**Note:** Not tested.
=> Add Spanish language support

web/src/i18n/languages.ts, web/src/i18n/locales/ja.ts
I've added a Japanese locale. If it looks good, please merge it. Thank you!
=> Add Japanese language support

web/src/i18n/languages.ts, web/src/i18n/locales/da.ts
100% translation of Danish language for the NanoKVM.
=> Add Danish language support

web/src/i18n/languages.ts, web/src/i18n/locales/id.ts
I've added a Indonesia locale. If it looks good, please merge it. Thank you!
=> Add indonesia language support

web/src/i18n/locales/en.ts, web/src/pages/auth/login/index.tsx
Changing the login button text to "Login" from "Ok"
=> Improve login button text

web/src/i18n/languages.ts, web/src/i18n/locales/zh_tw.ts
This PR adds supprt for Traditional Chinese (zh_tw)
=> Add support for Traditional Chinese (zh_tw)

README.md, README_JA.md, README_ZH.md, server/README_JA.md, web/README_JA.md
I created Japanese translated READMEs.
=> docs: add Japanese README files

server/proto/download.go, server/service/download/service.go, web/src/pages/desktop/menu/download.tsx
This will fix 22 error raised by tsc:
- remove unused rsp, err and List
- fix use of NodeJS.Timeout
- define proto for api responses
- use rsp.OkRspWithData instead of c.JSON
- fix handling api responses
=> Download image fixups

server/service/storage/image.go
First the image is unmounted by setting the file to empty string.
Then it will set set lun flags before mounting the image:
- removable (always on)
- ro (if /boot/usb.disk0.ro exists or cdrom image choosen)
- cdrom (depending on file extension)
=> server: storage: set device flags

web/src/i18n/locales/zh_tw.ts
Description:
- Added missing translations
- Refined existing translations for more natural language flow
- Improved consistency of terminology
Changes include:
- Translated previously untranslated strings
- Adjusted phrasing to better match Taiwanese language conventions
=> Update zhTW Translation

web/src/i18n/locales/ko.ts
This PR improves the Korean translation by making it more natural and consistent.
Untranslated strings have been localized, and commonly used UI terms have been applied for better user experience.
=> Update korean translations

server/service/auth/account.go
better readability for non GO developers who are interested to perform security reviews
=> refactored for readability

web/src/i18n/locales/ru.ts
Add missing keys to the ru.ts file as well as fix errors introduced by machine translation.
=> Update (and fix) Russian translation

web/src/i18n/locales/en.ts
=> Improve English strings in web interface

web/src/i18n/locales/en.ts, web/src/pages/desktop/menu/download.tsx, web/src/pages/desktop/menu/fullscreen/index.tsx, web/src/pages/desktop/menu/image/index.tsx, web/src/pages/desktop/menu/index.tsx, web/src/pages/desktop/menu/keyboard/index.tsx, web/src/pages/desktop/menu/mouse/index.tsx, web/src/pages/desktop/menu/power/index.tsx, web/src/pages/desktop/menu/screen/index.tsx, web/src/pages/desktop/menu/script/index.tsx, web/src/pages/desktop/menu/settings/index.tsx, web/src/pages/desktop/menu/terminal/index.tsx, web/src/pages/desktop/menu/wol/index.tsx
Added some tooltips to menu items for ease of use
=> Add tooltips to menu

kvmapp/system/update-nanokvm.py
- Fixed some wording
- Added use of "pathlib" library (which comes from Python standard library; no additional external dependency) to make managing files,directories,... easier
- Added use of type hint, to help devs comprehend the code with ease
=> Improve and optimize update-nanokvm.py

web/src/i18n/locales/en.ts, web/src/i18n/locales/pl.ts, web/src/pages/desktop/menu/terminal/serial-port.tsx, web/src/pages/terminal/index.tsx
Add support for parity, flow control, data bits and stop bits options.
=> Add more serial features

server/proto/vm.go, server/router/vm.go, server/service/vm/swap.go, web/src/api/vm.ts, web/src/i18n/locales/en.ts, web/src/i18n/locales/zh.ts, web/src/pages/desktop/menu/settings/device/index.tsx, web/src/pages/desktop/menu/settings/device/swap.tsx
#206 
Add Swap function in WEB UI,default size is 128M.
=> add the swap function in WebUI

web/src/assets/styles/index.css, web/src/pages/auth/login/index.tsx
=> Add logo to login screen

kvmapp/system/init.d/S95nanokvm
NEW state must be accepted on INPUT.
=> fix iptables for ssh

web/src/i18n/locales/uk.ts
Update translation into Ukrainian for version 2.2.6.
=> Update translation into Ukrainian for version 2.2.6.

web/src/i18n/locales/ko.ts
revised the korean text to make it more natural
=> revised some korean text

server/service/hid/paste.go
Code now relies solely on the modifier byte within the main keyDown report to signal that shift is active. This is a more reliable approach. Please be advised, also reworked on the mapping of how the characters are constructed.
=> Updated paste.go

web/src/i18n/locales/pt_br.ts
Adding Brazilian Portuguese translation.
=> Adding PT-BR translation
